### ISSUE TITLE
Allow exit of spending condition

### ISSUE THREAD

**Issue by eshavkun** [leapdao/leap-contracts#188] opened 2019-05-13 12:26 UTC
# Bounty
Currently it's not possiible for spending conditions to secure its funds in case of udesired network behavior. Spending condition should be allowed to exit all it's funds to the mainnet counterpart (smart contract).

## Deliverables
- Upgraded smart contracts (exit handler) with support of spending conditions exits.
- Spending condition template with example exit function

## Gain for the project
Spending conditions security increase

## Roles
bounty gardener: name / share
bounty worker: name / share
bounty reviewer: name / share

**Comment by johannbarbie** [comment] 2019-05-15 20:54
@eshavkun 
duplicate of https://github.com/leapdao/leap-contracts/issues/147 and https://github.com/leapdao/leap-contracts/issues/146 ?

**Comment by johannbarbie** [comment] 2019-05-19 05:18
closed for duplication

**Closed by johannbarbie** 2019-05-19 05:18 UTC
